spring.application.name=EventHub

server.port=8081

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=EventHub;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123

# Hibernate tu dong tao/cap nhat bang theo Entity
# Ae cam doi update thanh create ko la mat het du lieu database
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false