spring.application.name=EventHub

server.port=8081

#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.url=jdbc:sqlserver://localhost:1433;database=EventHub;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=true
#spring.datasource.username=sa
#spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://221.132.16.141:1433;databaseName=EventHub;encrypt=true;trustServerCertificate=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# Hibernate t? t?o/c?p nh?t b?ng theo Entity
# Ae c?m ??i cái update thành create ko mà m?t t?t data li?u ??y
spring.jpa.hibernate.ddl-auto= update

spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=10MB

spring.servlet.multipart.max-request-size=10MB



#thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false
spring.devtools.livereload.enabled=true

#setup cloud
cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_KEY}
cloudinary.api-secret=${CLOUDINARY_SECRET}


# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile


#Spring Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tuan040905@gmail.com
spring.mail.password=${APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



#checkout time
checkout.seat-lock.browse-minutes=5
checkout.seat-lock.payment-minutes=25
checkout.order.expires-minutes=25

#Viet_QR
vietqr.url-template=https://img.vietqr.io/image/{bank_bin}-{account_no}-compact2.jpg?amount={amount}&addInfo={payment_code}&accountName={account_name}


payment.bank-bin=970423
payment.account-number=13914092005

#Gemini API Key
gemini.api.key=${GEMINI_API_KEY}