spring.application.name=EventHub

server.port=8081

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=EventHub;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
# Hibernate t? t?o/c?p nh?t b?ng theo Entity
# Ae c?m ??i cái update thành create ko mà m?t t?t data li?u ??y
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true


#thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false